USE cafe;

CREATE TABLE Customers(CustomerID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
FirstName VARCHAR(50) NOT NULL, 
LastName VARCHAR(50) NOT NULL, 
Phone INT, 
Email VARCHAR(100) UNIQUE, 
Address VARCHAR(255));

CREATE TABLE Employees(EmployeeID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
FirstName VARCHAR(50) NOT NULL, 
LastName VARCHAR(50) NOT NULL, 
Phone VARCHAR(30), 
Email VARCHAR(100), 
CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE Menu(ItemName VARCHAR(255) NOT NULL, 
Category VARCHAR(255) NOT NULL, 
Price VARCHAR(255) NOT NULL,
Description VARCHAR(300));

CREATE TABLE Orders(OrderID ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
CustomerID INT NOT NULL, 
ItemName VARCHAR(255) NOT NULL, 
Quantity INT NOT NULL,
OrderStatus tinyint NOT NULL, 
OrderCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), 
OrderCompleted TIMESTAMP, 
INDEX `idx_order`(OrderID),
CONSTRAINT `fk_order_item`
FOREIGN KEY (ItemName)
REFERENCES Menu(ItemName) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT `fk_customer_id`
FOREIGN KEY (CustomerID)
REFERENCES Customers(CustomerID) ON UPDATE CASCADE ON DELETE RESTRICT
);
