version: "3"
services:
  api:
    build: ./api
    depends_on:
      - db
    container_name: api-353
    ports:
      - "80:8080"
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: cafe
      MYSQL_USER: root
      MYSQL_PASSWORD: beans101
    volumes:
      - ./api:/usr/src/app
    restart: on-failure
  db:
    build: ./database
    container_name: mysql-353
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/storage:/var/lib/mysql
  app:
    build: ./app
    container_name: app-353
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    restart: on-failure
